name: makewaves
channels:
- defaults
dependencies:
- asn1crypto=0.22.0=py27hc975345_1
- ca-certificates=2017.08.26=h94faf87_0
- cachecontrol=0.12.3=py27h15eca11_0
- certifi=2017.7.27.1=py27hf761292_0
- cffi=1.10.0=py27hb6f203f_1
- chardet=3.0.4=py27h56c3b73_1
- colorama=0.3.9=py27hdfe4ae1_0
- cryptography=2.0.3=py27h1cc6ae9_1
- distlib=0.2.5=py27hbc39c7c_0
- enum34=1.1.6=py27h2aa175b_1
- html5lib=0.999999999=py27h47766b3_0
- icc_rt=2017.0.4=h97af966_0
- idna=2.6=py27h1ea29d3_1
- intel-openmp=2018.0.0=hcd89f80_7
- ipaddress=1.0.18=py27h08e1fa7_0
- jpeg=8d=vc9_2
- libpng=1.6.32=vc9h2352712_3
- libtiff=4.0.6=vc9_2
- lockfile=0.12.2=py27hcad0c83_0
- mkl=2018.0.0=h36b65af_4
- msgpack-python=0.4.8=py27he0366a1_0
- numpy=1.13.3=py27h9ac254c_0
- openssl=1.0.2l=vc9h02d068b_2
- packaging=16.8=py27hae1a450_1
- pip=9.0.1=py27hdb66070_3
- progress=1.3=py27hcb558ea_0
- pycparser=2.18=py27hb43d16c_1
- pyopenssl=17.2.0=py27h58ddd18_0
- pyparsing=2.2.0=py27hc7d9fa6_1
- pyqt=4.11.4=py27_7
- pysocks=1.6.7=py27h59bdd1e_1
- python=2.7.14=h59f5a59_20
- qt=4.8.7=vc9_9
- requests=2.18.4=py27h3159eba_1
- setuptools=36.5.0=py27ha483b79_0
- sip=4.18=py27_0
- six=1.10.0=py27h5de879c_1
- urllib3=1.22=py27hb9f5a07_0
- vc=9=h7299396_0
- vs2008_runtime=9.00.30729.1=hfaea7d5_0
- webencodings=0.5.1=py27h4e224a2_1
- wheel=0.29.0=py27hffb40b6_1
- win_inet_pton=1.0.1=py27hf41312a_1
- wincertstore=0.2=py27hf04cefb_0
- zlib=1.2.11=vc9ha80f4e8_1
- pip:
  - pydaqmx==1.3.2
  - pyqwt==5.2.1
  - win-inet-pton==1.0.1
